name: build

on:
  push:
    paths:
      - "docker.mk"
      - "Dockerfile"
      - "scripts/**"
    branches:
      - master
  pull_request:
    paths:
      - "docker.mk"
      - "Dockerfile"
      - "scripts/**"
    branches:
      - master

jobs:
  dpdk:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make -e BUILDER_BASE_IMG=ubuntu:bionic -f docker.mk build-dpdk

      - name: publish
        if: github.event_name == 'push'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          make -f docker.mk push-dpdk
          make -f docker.mk push-dpdk-latest

  dpdk-devbind:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make -e BUILDER_BASE_IMG=ubuntu:bionic -f docker.mk build-devbind

      - name: publish
        if: github.event_name == 'push'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          make -f docker.mk push-devbind
          make -f docker.mk push-debind-latest

  dpdk-install:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: run-setup
        shell: bash
        run: |
          ./scripts/setup.sh

      - name: install-dpdk
        shell: bash
        run: ./scripts/dpdk.sh

      - name: check-install
        run: dpdk-devbind.py --status

  # TODO: build-out matrix of kernel versions when we build them out-of-tree
  dpdk-mod:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make -e BUILDER_BASE_IMG=ubuntu:bionic -f docker.mk build-mod

  sandbox:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: make -e BUILDER_BASE_IMG=ubuntu:bionic -f docker.mk build-sandbox

      - name: test-capsule-in-sandbox
        run: make -f docker.mk test-sandbox

      - name: publish
        if: github.event_name == 'push'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          make -f docker.mk push-sandbox
          make -f docker.mk push-sandbox-latest

  discord:
    needs: [dpdk, dpdk-devbind, dpdk-install, dpdk-mod, sandbox]
    runs-on: ubuntu-18.04
    steps:
      - name: discord-it
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: "*${{ github.workflow }} Succeeded!* ~ ${{ github.HEAD_REF }} by ${{ github.ACTOR }} ~ https://github.com/capsule-rs/sandbox/actions"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
